// This file is "main.dart"
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'unfreezed_ex.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'unfreezed_ex.g.dart';

@unfreezed
class Client with _$Client {
  factory Client({
    required String firstName,
    required String lastName,
    required final int age,
  }) = _Client;

  factory Client.fromJson(Map<String, Object?> json) => _$ClientFromJson(json);
}

Client client = Client(firstName: 'firstName', lastName: 'lastName', age: 32);
void change(){
  client.lastName = '14';
}